services:
  - type: web
    name: currency-converter-api
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: JWT_SECRET
        sync: false
      - key: EXCHANGE_API_KEY
        sync: false
      - key: ENVIRONMENT
        value: production
    healthCheckPath: /api/health
